
import Head from "next/head";
import 'bootstrap/dist/css/bootstrap.min.css';
import Footer from "../Components/footer";
import Nav from '../Components/nav';



const Layout = (props) => {
  return (
    <>
      <Head>
        <title>Nick Adams</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
       <Nav />
      {props.children}
      <Footer />

    </>



  )
}

export default Layout;