
import Head from "next/head";
import 'bootstrap/dist/css/bootstrap.min.css';
import Button from 'react-bootstrap/Button';
import Nav from '../Components/nav'


const Layout = (props) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      
      {props.children}
      <nav />
      <Button variant="primary" id="btn">Primary</Button>
      <h1>Hello!</h1>

      <style jsx>
        {`
     
     h1 {
       color: green;
     }

     #btn {
       margin: 20px;
       color: green;
     }

  
        
        `}
      </style>

    </>



  )
}

export default Layout;